// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PrintAPI is an autogenerated mock type for the PrintAPI type
type PrintAPI struct {
	mock.Mock
}

// PrintSomething provides a mock function with given fields:
func (_m *PrintAPI) PrintSomething() {
	_m.Called()
}

type mockConstructorTestingTNewPrintAPI interface {
	mock.TestingT
	Cleanup(func())
}

// NewPrintAPI creates a new instance of PrintAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPrintAPI(t mockConstructorTestingTNewPrintAPI) *PrintAPI {
	mock := &PrintAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
